name: toby

on:
  workflow_dispatch:
    branches: [main]

env:
  IMAGE_REPO: us.icr.io/research/macq
  IMAGE_NAME: toby

jobs:
  setup-build-push-deploy:
    name: Setup, Build, Push, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compute sha
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=current_time::$(date +%s%3N)"
      - name: Build a docker image
        env:
          IMAGE_TAG: ${{steps.vars.outputs.sha_short}}${{steps.vars.outputs.current_time}}
        run: docker build -t $IMAGE_REPO/$IMAGE_NAME":"$IMAGE_TAG .
        working-directory: ./src/server
      - name: Setup IBM Cloud CLI
        env:
          API_KEY: ${{ secrets.IBM_API_KEY }}
          INSTALL_PLUGINS: code-engine,container-service, container-registry
          REGION: us-south
          RESOURCE_GROUP: CUELAB
        run: |
          sudo apt update
          sudo apt install -y curl
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          bx plugin install container-registry
          bx plugin install container-service
          bx plugin install code-engine
          bx login --apikey $API_KEY -r $REGION -g $RESOURCE_GROUP
          bx cr region-set $REGION
          bx cr login
          bx target
      - name: Push docker image
        env:
          IMAGE_TAG: ${{steps.vars.outputs.sha_short}}${{steps.vars.outputs.current_time}}
        run: docker push $IMAGE_REPO/$IMAGE_NAME":"$IMAGE_TAG
      - name: Update container image
        env:
          APP_NAME: toby
          PROJECT_NAME: macq
          IMAGE_TAG: ${{steps.vars.outputs.sha_short}}${{steps.vars.outputs.current_time}}
          APP_REGION: us-east
          APP_RESOURCE_GROUP: CUELAB
          REPOSITORY_ACCESS_SECRET_NAME: macq2
        run: |
          bx target -r $APP_REGION -g $APP_RESOURCE_GROUP
          bx ce project select -n $PROJECT_NAME
          bx ce app update -n $APP_NAME -i $IMAGE_REPO/$IMAGE_NAME":"$IMAGE_TAG --rs $REPOSITORY_ACCESS_SECRET_NAME
